
SOURCES = fileicons.png jsw.bmp jswed.ico jswed.png jswed_logo.png \
	  room_v.hex room_w.hex room_x.hex room_y.hex room_z.hex room_yy.hex \
	  rtime7v.bin rtime7w.bin rtime7x.bin rtime7y.bin rtime7z.bin \
	  rtime7yy.bin COPYING

install-data-local:
	$(mkinstalldirs) $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/jsw.bmp   $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/jswed.ico $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/jswed.png $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/jswed_logo.png $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/fileicons.png $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/room_v.hex   $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/room_w.hex   $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/room_x.hex   $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/room_y.hex   $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/room_z.hex   $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/room_yy.hex  $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/rtime7v.bin  $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/rtime7w.bin  $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/rtime7x.bin  $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/rtime7y.bin  $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/rtime7z.bin  $(datadir)/jswed
	$(INSTALL_DATA) $(srcdir)/rtime7yy.bin  $(datadir)/jswed

